newrelic/newrelic-cli

Makefile, build/compile.mk, build/package.mk
Create artifacts to be added to the releases via the build system
=> chore(build): Add zip packaging to build system

go.mod, go.sum
Update newrelic-client-go to 0.12.0
=> Update newrelic-client-go to 0.12.0

internal/config/config.go, internal/config/config_integration_test.go, internal/config/helpers.go
Resolves #68 . 
This PR refactors the config code for testability and adds several integration tests.
=> refactor(config) refactor for testability and add tests

Makefile, build/release.mk, build/test.mk, cmd/newrelic/command.go, cmd/newrelic/main.go, internal/client/client.go, internal/version/version.go, internal/version/version_test.go, tools/release.sh
=> fix(config): set user agent and service name, add version package

.circleci/config.yml, build/docker.mk
* Update the Container name to `newrelic/cli`
* Update CircleCI config for building docker / pushing the container
=> Build Docker container

internal/apm/command.go, internal/apm/command_test.go
=> feat(apm): include get and list commands for APM applications

CHANGELOG.md, internal/version/version.go
- **client:** Fix ENV var prefix to be consistent with NR standards
- **config:** set user agent and service name, add version package
- **credentials:** proper handling when removing default profile
- **docs:** Fix release badge link
- **command:** improve short help text
- **apm:** include get command for APM applications
- **docker:** Add docker image building / push to make system
=> Release 0.2.0

internal/config/config.go
Resolves #99 .
This PR fixes some internal config logic so that the tests no longer overwrite the actual configuration file.
=> tests(config): fix tests that were overriding actual config files

internal/entities/command.go, internal/utils/utils.go, internal/utils/utils_test.go
=> feat(entities): add ability to map entity search result fields via flag

cmd/newrelic/command_completion.go, cmd/newrelic/command_version.go, internal/apm/command.go, internal/apm/command_application.go, internal/apm/command_deployment.go, internal/config/command.go, internal/credentials/command.go, internal/entities/command.go, internal/entities/command_search.go, internal/entities/command_tags.go, internal/nerdgraph/command.go, internal/nerdgraph/command_query.go
This PR updates the help screens for consistency.
=> docs(newrelic): update the help screens for consistency

internal/apm/command_application.go, internal/apm/command_application_test.go, internal/apm/command_deployment.go, internal/apm/command_deployment_test.go, internal/config/command_test.go, internal/credentials/command.go, internal/credentials/command_test.go, internal/entities/command_search.go, internal/nerdgraph/command.go, internal/nerdgraph/command_query.go, internal/nerdgraph/command_query_test.go, internal/nerdgraph/command_test.go, internal/testcobra/testcobra.go, internal/utils/utils.go
Changes to most commands for variable names, improved testing, and syntax changes for the commands.
=> Variable names, Test Updates, Reformats Oh my

internal/apm/command_application.go, internal/entities/command_search.go
=> Print help when required filter flags are empty

internal/config/command.go, internal/credentials/command.go, internal/entities/command_tags.go
=> chore(success): print a success message on commands lacking output

internal/credentials/credentials.go, internal/credentials/profiles_integration_test.go
=> Lowercase Region in profile

Makefile, build/admin.mk, build/release.mk
The admin-homebrew script wasn't working, so I modified it a bit and migrated it into `release-homebrew` with the other release creating stuff.
=> Minor homebrew refactor

build/lint.mk, go.mod, go.sum, internal/credentials/credentials.go, internal/credentials/helpers.go, internal/credentials/profiles.go, internal/entities/command_tags_test.go, tools.go
* Add goimports to the linting run
* Fix all of the existing import issues
* Update linting / release libraries
=> Build: Add goimports

renovate.json
This PR adds a renovate config.
=> chore(newrelic): add renovate bot

CHANGELOG.md
=> chore(changelog): Update CHANGELOG for v0.5.0

.github/workflows/security.yml, .github/workflows/test.yml
Exploratory testing of GitHub actions for the test workflow.
=> Setup testing of the CLI via GitHub Actions

cmd/newrelic/main.go, go.mod, go.sum, internal/client/client.go, internal/nerdstorage/command.go, internal/nerdstorage/command_collection.go, internal/nerdstorage/command_collection_test.go, internal/nerdstorage/command_document.go, internal/nerdstorage/command_document_test.go, internal/nerdstorage/command_test.go
Resolves #62 .
This PR adds support for nerdstorage operations in the CLI.
=> feat(nerdstorage): add support for nerdstorage operations

CHANGELOG.md
=> chore(changelog): Update CHANGELOG for v0.6.0

go.mod, go.sum, internal/client/client.go, internal/credentials/command.go, internal/credentials/credentials.go, internal/credentials/profiles.go, internal/credentials/profiles_integration_test.go, internal/credentials/profiles_test.go
=> fix(profile): Fix case sensitivity of region

.goreleaser.yml, build/release.mk, cmd/newrelic/command.go
=> fix(newrelic): Fix command name replacement on build

README.md, scripts/install.sh
resolves: #169
Here we include a simple install script to download the latest release from
GitHub and move the binary to the desired location.
Heavily borrowed from CircleCI.
https://github.com/CircleCI-Public/circleci-cli
=> feat(install): include install script

.github/workflows/release.yml, scripts/brew_formula_pull_request.sh
=> feat(ci): automate updating of homebrew formula

README.md
This PR updates the README's installation section with more options.
=> docs(installation): update installation guide with more options

docs/GETTING_STARTED.md
=> docs: update command examples in Getting Started guide

.github/workflows/release.yml, .gitignore, Makefile, build/chocolatey.mk, build/package/chocolatey/newrelic-cli.nuspec, build/package/chocolatey/tools/VERIFICATION.txt, build/package/chocolatey/tools/chocolateybeforemodify.ps1, build/package/chocolatey/tools/chocolateyinstall.ps1
relates to: https://github.com/newrelic/newrelic-cli/issues/170
=> feat(chocolatey): begin chocolatey build

.github/workflows/release.yml, .goreleaser.yml
This PR adds code signing for build artifacts generated by goreleaser.
=> feat(release): add code signing for artifacts

.github/stale.yml
=> chore(build): Add stale bot config

docs/extensions.md
=> docs(extensions): add cli extension documentation

go.mod, go.sum
Updating newrelic-client-go and other dependencies.
=> chore: update newrelic-client-go and other dependencies

.github/workflows/release.yml, .github/workflows/test.yml
Instead of a step to unshallow.
=> Update actions/checkout to fetch all the history by default

.github/workflows/snapshot.yml, README.md, build/docker.mk, go.mod, go.sum, internal/config/table_renderer.go
Whenever master is merged, build / publish `newrelic/cli:snapshot` to Docker Hub.
=> Create docker Snapshot image from master

.github/renovate.json, build/compile.mk, go.mod, go.sum
* Update to newrelic-client-go
* Update tools
* Disable CGO for all build targets
* Update Renovate config for our linting rules.
=> Update newrelic-client-go to v0.26.0

internal/config/config.go, internal/config/config_integration_test.go
=> chore(config): Cleanup comment / consistent naming

cmd/newrelic/command.go
=> refactor(newrelic): dont display help usage in CI to avoid noise

.github/workflows/newrelic_homebrew_core_rebase.yml, scripts/brew_formula_pull_request.sh, scripts/rebase_from_upstream.sh
This PR introduces automation for syncing `newrelic-forks/homebrew-core` with the upstream `Homebrew/homebrew-core` repo to facilitate smoother release automation.
=> feat(release): automate syncing our homebrew-core fork 

internal/config/config.go, internal/config/config_integration_test.go
=> fix(config): ensure compatible case with nr1

go.mod, internal/edge/command.go
=> feat: release edge command

cmd/newrelic/main.go, docs/GETTING_STARTED.md, go.mod, internal/client/client.go, internal/client/client_integration_test.go, internal/client/helpers.go, internal/credentials/command.go, internal/credentials/credentials.go, internal/credentials/profiles.go, internal/credentials/profiles_integration_test.go, internal/events/command.go, internal/events/command_post.go, internal/events/command_post_test.go, internal/events/command_test.go
This required the addition of additional credentials to the profile (Insights insert key), so some work has been done in that area as well.
=> feat: add a command for posting custom events

go.mod, go.sum, internal/install/install.go, internal/install/mock_nerdgraph_client.go, internal/install/mock_recipe_fetcher.go, internal/install/nerdgraph_client.go, internal/install/process_filterer.go, internal/install/psutil_discoverer.go, internal/install/recipe_fetcher.go, internal/install/regex_process_filterer.go, internal/install/regex_process_filterer_test.go, internal/install/service_recipe_fetcher.go, internal/install/service_recipe_fetcher_test.go, internal/utils/utils.go
Depends on newrelic/newrelic-client-go#563
=> Allow passing client context to recipe service client methods

internal/install/command.go, internal/install/recipe_installer.go
=> chore(install): refactor install steps for clarity

internal/config/config.go, internal/config/logging.go
This change follows the approach outlined [here](https://github.com/Sirupsen/logrus/issues/230).
=> chore(install): write log messages to file

internal/install/discovery/psutil_discoverer.go, internal/install/recipe_installer.go, internal/utils/utils.go
=> chore(install): exit immediately when sigint received during prompt

internal/install/command.go, internal/install/execution/go_task_recipe_executor.go, internal/install/execution/go_task_recipe_executor_test.go, internal/install/execution/mock_recipe_executor.go, internal/install/execution/recipe_executor.go, internal/install/install_context.go, internal/install/recipe_installer.go
Included here is a new command flag which will allow the user to accept all
prompts using default values if none are set in the environment to use instead.
=> feat(install): add -y flag

cmd/newrelic/main.go, docs/cli/newrelic_decode.md, docs/cli/newrelic_decode_entity.md, internal/decode/command.go, internal/decode/command_entity.go, internal/decode/command_entity_test.go, internal/decode/command_test.go, internal/decode/command_url.go, internal/decode/command_url_test.go
Created this PR to create Decode CLI operation -> #623
=> feat(decode): NR CLI Translate base64 encoded urls command

README.md
- instruct on how to obtain
- instruct on how to verify
=> chore: add pgp key fingerprint

internal/install/execution/terminal_reporter.go
The UI says Data gap and not Detected observability gaps
=> fix: Replace Detected observability gaps by Data Gaps

internal/install/execution/install_status.go, internal/install/execution/mock_success_link_generator.go, internal/install/execution/success_link_generator.go, internal/install/execution/terminal_reporter.go, internal/install/execution/terminal_reporter_test.go, internal/install/recipe_installer_targeted.go, internal/install/recipes/recipe_file.go, internal/install/scenario_builder.go, internal/install/types/recipe.go, internal/install/types/types.go, internal/utils/utils.go
`./bin/darwin/newrelic installTest -s DISPLAY_EXPLORER_LINK -n test-display-explorer-link`
An end to end test against the java APM recipe can also be used.
=> feat(install): display filtered explorer link

internal/install/execution/go_task_recipe_executor.go, test/recipes/testStdin.yaml
Compile and test this with:
```
newrelic installTest -c ./test/recipes/testStdin.yaml
```
cc @joshuabenuck
=> feat(install): enable stdin piping for install command

internal/install/execution/install_status.go, internal/install/execution/terminal_reporter.go, internal/install/execution/terminal_reporter_test.go, internal/install/recipes/recipe_file.go, internal/install/scenario_builder.go, internal/install/types/recipe.go, internal/install/types/types.go
Updating `successLink` -> `successLinkConfig` and updating docs per UAPI feedback.
cc @michaelkro
=> chore(install): update recipe schema with successLink field

docs/cli/newrelic_install.md, docs/cli/newrelic_installTest.md, internal/install/command.go, internal/install/install_context.go, internal/install/install_context_test.go, internal/install/recipe_installer_guided.go, internal/install/recipe_installer_test.go, internal/install/test_command.go, internal/install/types/recipe.go
https://newrelic.atlassian.net/browse/VIRTUOSO-679
=> feat(install): add skip apm option and skip any APM recipe when set

internal/install/recipe_installer_guided.go, internal/install/recipe_installer_targeted.go, internal/install/recipe_installer_test.go, internal/install/recipes/service_recipe_fetcher.go, internal/install/types/recipe.go
https://newrelic.atlassian.net/browse/VIRTUOSO-660
=> fix(install): update user message when failing to find a valid infra or logging recipe for the host

internal/install/recipes/service_recipe_fetcher.go
https://newrelic.atlassian.net/browse/VIRTUOSO-728
=> chore(install): allow the kernel properties when fetching recipes

internal/install/recipe_installer.go, internal/install/recipe_installer_test.go, internal/install/recipes/recipe_repository.go, internal/install/recipes/recipe_repository_test.go, internal/install/types/recipe.go, newrelic-cli.json
https://newrelic.atlassian.net/browse/VIRTUOSO-1054
=> fix(install): capture first error and report in tessen

internal/install/recipe_installer.go
https://newrelic.atlassian.net/browse/VIRTUOSO-1071
=> fix(install): install infra when skip all

internal/install/discovery/manifest_validator.go, internal/install/discovery/mock_discoverer.go, internal/install/execution/go_task_recipe_executor.go, internal/install/execution/install_status.go, internal/install/execution/mock_recipe_executor.go, internal/install/execution/mock_status_reporter.go, internal/install/execution/nerdstorage_status_reporter.go, internal/install/execution/status_subscriber.go, internal/install/execution/terminal_reporter.go, internal/install/recipe_installer.go, internal/install/recipe_installer_test.go, internal/install/types/discovery_manifest.go, internal/install/types/errors.go
=> feat(install): add UNSUPPORTED status

scripts/install.sh
https://newrelic.atlassian.net/browse/VIRTUOSO-1028
=> chore(install): prompt and install curl if needed

internal/install/execution/installevents_reporter.go
Fixing the infamous issue that we've been seeing when integrating the `install-events-service`:
```golang
ERROR Could not report recipe execution status: Argument "status" has invalid value $status.
In field "status": Expected type "InstallationRecipeStatusType!", found "".
```
I believe the `Observability<...>` implementations are not necessary at the moment, as we will be adding a separate mutation to the new service. 
Depends on [this PR](https://github.com/newrelic/newrelic-client-go/pull/775).
=> refactor: updates to install events reporter

internal/install/discovery/manifest_validator.go
Adding validation with the minimum versions of the infra agent https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/get-started/requirements-infrastructure-agent/
https://newrelic.atlassian.net/browse/VIRTUOSO-1178
=> chore(install): detect and validate for unsupported linux versions

internal/install/types/types.go
Update generated code using tutone
- make generate
- PR generated by [create-pull-request][1]
[1]: https://github.com/peter-evans/create-pull-request
=> chore(tutone): update generated code

internal/utils/http_client.go
https://newrelic.atlassian.net/browse/VIRTUOSO-1384
=> fix(install): handle canceled validation when nrql completes first

.github/workflows/release.yml, .github/workflows/test.yml
Order of operations:
```
TEST (parallel jobs) ---> E2E (parallel jobs)  ---> RELEASE
```
=> chore(release): parallelize test jobs

internal/install/recipes/recipe_repository.go, internal/install/recipes/recipe_repository_test.go
To support specific linux arm versions for the log recipe https://github.com/newrelic/open-install-library/pull/570
=> feat(install): allow recipe target to define a regular expression for matching

internal/install/execution/link_generator.go, internal/install/execution/mock_link_generator.go, internal/install/execution/platform_link_generator.go, internal/install/execution/platform_link_generator_test.go, internal/install/execution/terminal_reporter.go, internal/install/execution/terminal_reporter_test.go, internal/install/interfaces.go, internal/utils/utils.go
=> feat(install): add logging url to installation summary

internal/install/execution/platform_link_generator.go, internal/install/execution/platform_link_generator_test.go
Adding the referrer parameter so we can send an event in the logging ui for this :)
=> feat(install): Add Logging referrer param

scripts/install.ps1
This adds the requires tag for admin for powershell.
=> feat(install): Require powershell to be run as admin

.github/workflows/release.yml, build/package/msi/NewRelicCLIInstaller/SignPS1.cmd
https://newrelic.atlassian.net/browse/VIRTUOSO-2011
=> fix(release): digitally sign install.ps1 script to fix windows installations

internal/cli/version.go, scripts/install.ps1
related PRs 
https://github.com/newrelic/open-install-library/pull/673
https://source.datanerd.us/open-source/nr1-install-newrelic/pull/640
=> chore(install): add tls13 to the protocol list for windows download

cmd/newrelic/command.go, go.mod, go.sum, internal/diagnose/config_validator.go, internal/diagnose/errors.go, internal/diagnose/helpers.go, internal/events/command_post.go, internal/install/command.go, internal/install/execution/platform_link_generator.go, internal/install/execution/platform_link_generator_test.go, internal/install/recipe_install_builder.go, internal/install/recipe_installer.go, internal/install/recipe_installer_test.go, internal/utils/retry.go, internal/utils/retry_test.go
Depends on [newrelic-client-go #866](https://github.com/newrelic/newrelic-client-go/pull/866)
=> feat(install): handle data usage exceeded scenario

.githooks/pre-commit, internal/diagnose/helpers.go, internal/install/execution/go_task_recipe_executor.go, internal/install/execution/mock_recipe_executor.go, internal/install/execution/output_parser.go, internal/install/execution/output_parser_test.go, internal/install/execution/recipe_executor.go, internal/install/execution/sh_recipe_executor.go, internal/install/recipe_install_builder.go, internal/install/recipe_installer.go, internal/install/recipe_installer_test.go, internal/utils/retry_test.go
[NR-3444](https://issues.newrelic.com/browse/NR-3444)
=> feat(install): ability to get recipe output data back (#1287)

internal/install/execution/recipe_var_provider.go, internal/install/execution/recipe_var_provider_test.go
Pass NRIA_CUSTOM_ATTRIBUTES and NRIA_PASSTHROUGH_ENVIRONMENT cli args to recipe context
=> feat(envars):  Add optional CLI envars to recipe context

internal/install/execution/install_status.go, internal/install/execution/terminal_reporter.go, internal/install/recipe_installer.go, internal/install/recipe_installer_test.go
Send recommended status for target install recipe; this shows additional instrumentation options for targeted install.
Recommended recipes are recipes available to be installed via CLI but not targeted during target install.
Have another UI ticket to show the recommended recipes.
=> chore(Install): Send recommended status for target install

internal/install/recipe_installer.go
https://issues.newrelic.com/browse/NR-31815
=> fix(install): ensure host has name for installations

internal/entities/command_deployment.go
Small PR to remove warning now the new deployment API is going GA.
=> chore(entity_deployment): remove limited preview warning

internal/utils/terraform/dashboard.go, internal/utils/terraform/hcl_gen.go
Added missed Raw Configuration properties to dashboard widget.
1. yaxisleft
2. Legend
3. null values
4. colors
5. units
6. facet
7. platformoptions
=> chore: added missing dashboard raw configuration fields

internal/apm/command_application.go
=> fix(apm): code correction to refactor error handling in apm 'search'

README.md
=> chore: fix broken link in README to PGP public key

internal/install/recipe_installer.go, internal/install/recipe_installer_test.go, internal/install/types/recipe.go
Preparing for new OTEL recipe for targeted install only
=> chore(install): Skip OTEL if not targeted

.github/workflows/release-homebrew.yml, .github/workflows/release-publish-windows.yml, .github/workflows/release-windows-installer.yml, .github/workflows/release.yml
This PR refactors our release pipeline to have a primary release workflow that's followed by multiple secondary release flows that will run in parallel. This should dramatically speed up our overall release pipeline.
Current release pipeline duration is approximately 43 minutes.
Goal release pipeline duration is approximately 20-25 minutes.
=> refactor(release): release pipeline optimizations

.github/workflows/e2e-eu.yml, .github/workflows/e2e.yml
- Allow better debugging and re-trigger individual tests when fail
=> chore: Update e2e testing workflow to run tests in parallel

go.mod, go.sum, internal/entities/command_deployment.go, internal/entities/command_deployment_test.go
This reverts commit a37c703defb07f97f5702be2d7a7b1306270d5e5.
=> Revert "feat(entities): Support custom attributes JSON (#1526)"

internal/install/execution/installevents_reporter_integration_test.go, internal/install/execution/mock_nerdstorage_client.go, internal/install/execution/nerdstorage_client.go, internal/install/execution/nerdstorage_status_reporter.go, internal/install/execution/nerdstorage_status_reporter_integration_test.go, internal/install/execution/nerdstorage_status_reporter_unit_test.go, internal/install/recipe_installer.go
Reverts newrelic/newrelic-cli#1550
=> Revert "Stop entity-scoped nerdstorage writes"

.goreleaser.yml, build/release.mk
Try debugging release pipeline [error](https://github.com/newrelic/newrelic-cli/actions/runs/8069906445/job/22046132006#step:8:541) with GoReleaser:
```
release failed after 0s                  error=git is in a dirty stat
Please check in your pipeline what can be changing the following files:
M scripts/win_metadata_files_remove.sh
```
=> chore(build): Try debugging release pipeline

.github/workflows/release.yml, .goreleaser.yml, build/release.mk
Clean up debug options and add a few comments on release process, related to the Windows binary metadata.
=> chore(release): Debug options clean up and add some comments

internal/install/recipe_installer.go, internal/install/recipes/mock_process_evaluator.go, internal/install/recipes/process_evaluator.go, internal/install/recipes/process_evaluator_test.go
Detect whether the `newrelic-super-agent` process is already running on host (Ref:[NR-217604](https://new-relic.atlassian.net/browse/NR-217604)).
[NR-217604]: https://new-relic.atlassian.net/browse/NR-217604?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(install): Detect super-agent is already running on host

internal/install/command.go, internal/install/types/recipe.go
Do not install both infra and super agents in a single install (Ref.: [NR-222479](https://new-relic.atlassian.net/browse/NR-222479)).
[NR-222479]: https://new-relic.atlassian.net/browse/NR-222479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(install): Do not simultaneously install infra and super agents

CHANGELOG.md
This reverts commit 319a0c41952618928724a8494374735169556370.
=> chore(changelog): revert 'update CHANGELOG for v0.79.0' 

.github/workflows/release-windows-installer.yml
Reverts newrelic/newrelic-cli#1588
=> chore(release): Add step to fetch from remote

go.mod, go.sum
=> feat(build): upgrade newrelic-client-go to 2.33.0 to fix install issues

go.mod, go.sum, internal/entities/command_deployment.go
Reverts PR newrelic/newrelic-cli#1605 (in response to https://github.com/newrelic/newrelic-cli/issues/1606)
=> chore: revert "feat(entity): Entity guid validation" (#1605)

go.mod, go.sum
(commit has `fix` because there is no other commit on main to be pushed into the release, having this as a `chore` would not help the release succeed)
=> fix: upgrade newrelic-client-go version to 2.36.2

.github/workflows/release.yml
JIRA: https://new-relic.atlassian.net/browse/NR-272393
=> chore: Removed needs attribute in the snapshot job

go.mod, go.sum, internal/install/command.go
Pass/use an existing license key, if present, when installing the infra agent.
=> feat: Use licenseKey if present in configuration

docs/GETTING_STARTED.md, internal/install/types/errors.go
Ticket : [NR-302745](https://new-relic.atlassian.net/browse/NR-302745)
Update CLI Docs to encourage customers to use `https` proxy using the environment variable `HTTPS_PROXY`
[NR-302745]: https://new-relic.atlassian.net/browse/NR-302745?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs(proxy-config): Update proxy configuration documentation

internal/utils/utils.go, internal/utils/utils_test.go
Fixes an issue in verifying EU license key validity.
=> fix: Eu license keys

internal/install/bundle_installer.go, internal/install/bundle_installer_test.go, internal/install/command.go, internal/install/execution/terminal_reporter.go, internal/install/execution/terminal_reporter_test.go, internal/install/recipe_installer.go, internal/install/recipe_installer_test.go, internal/install/recipes/bundler.go, internal/install/recipes/bundler_test.go, internal/install/recipes/recipe_repository.go, internal/install/recipes/recipe_repository_test.go, internal/install/types/errors.go, internal/install/types/recipe.go
This PR, renames Super Agent to Agent Control.
=> fix(agent-control): rename Super Agent to Agent Control in the CLI

.github/workflows/release-windows-installer.yml
- Bumped windows download artifact version to v4
=> fix: Bumped windows download artifact version to v4

.github/workflows/release-publish-windows.yml, .github/workflows/release.yml
- Updated awscli install command due to deprecation of awscli in ubuntu 24.04.
Ref: https://liberiangeek.net/2024/04/install-aws-cli-ubuntu-24-04/
=> fix: Updated awscli command in rel ymls

internal/nerdgraph/command_query.go
https://github.com/newrelic/newrelic-cli/issues/1568
=> feat(nerdgraph): Add support to output results for mutations in CLI

internal/install/types/types.go
This PR aims to add fedora support in platform and platformFamily.
=> feat(fedora-support): add fedora support in platform and platformFamily

.github/workflows/release.yml
This is a PR that include minor update where we are adding a new step in the release.yml file to copy the checksum file with a different name and push it to GIT release assets along with its respective signature file.
This changes are done for the minor request that was asked by the customer(E.ON) in this [WR](https://new-relic.atlassian.net/browse/NR-307933).
Changes for the checksum generation and adding the install scripts to the GIT release assets was done as part of https://github.com/newrelic/newrelic-cli/pull/1736 PR.
No Test validation SS is available as there is no way to test the changes in local, a realtime release is required to test the changes..
Any further changes on this will be part of other PR and this PR will be attached in the new one to keep a track of the PR's that …
=> feat(checksum): Update checksum signing config
