README.md
internal/client/client.go

The engineering standard for Environment variable prefixes at New Relic is `NEW_RELIC_`. Update the API Key and Region variables to use this prefix instead (and remove `Personal` from the env var name for the API key)

fix(client): Fix ENV var prefix to be consistent with NR standards

---

Dockerfile
README.md

We were using CMD for specifying the command to run inside the container which requires the user to specify the binary name again when running.  This removes that behavior.

Fix: Docker entrypoint

---

CHANGELOG.md
internal/version/version.go

- **docker:** Use Entrypoint so binary is assumed

Release v0.2.1

---

CHANGELOG.md
tools/release.sh

- **build:** Remove version.go generation from make release
- **build:** Add docker login to release-push process

Release v0.2.2

---

Makefile

Homebrew formula require local build of the binary from a tar.gz of the source.  We currently get the version from the latest git tag, so this breaks.
Change PROJECT_VER to allow it to be overridden on make.

Allow overriding the version on make

---

cmd/newrelic/main.go
internal/entities/command.go
internal/nerdgraph/command.go
internal/nerdgraph/command_test.go

Depends on PR [#147](https://github.com/newrelic/newrelic-client-go/pull/147) in **newrelic-client-go** being released.
Resolves: #60
Resolves: #84 
Example command:
```
newrelic nerdgraph query "{ actor { user { email id name } } }"
```

feat(nerdgraph): add nerdgraph command with query subcommand

---

cmd/newrelic/command.go

Addresses line item from #49 
> Address duplication of errors (top & bottom of stderr output)

fix(newrelic): avoid duplicate error message output

---

cmd/newrelic/main.go

Minor issue, but entirely distracting to me...
```
$ ./bin/darwin/newrelic entities
Interact with New Relic entities
Usage:
newrelic entities [command]
Available Commands:
create-tags       Create tag:value pairs for the given entity
delete-tag-values Delete the given tag/value pairs from the given entity
delete-tags       Delete the given tag:value pairs from the given entity
describe-tags     Describe the tags for a given entity
replace-tags      Replace tag:value pairs for the given entity
search            Search for New Relic entities
Flags:
-h, --help   help for entities
Use "newrelic entities [command] --help" for more information about a command.
FATA[0000] subcommand is required
```
That Last Line ^^^
```
$ ./bin/darwin/newrelic entities
Interact with New Relic entities
Usage: …
```

Do not log fatal error if Cobra is printing out the help

---

internal/entities/command.go
internal/entities/command_search.go
internal/entities/command_search_test.go
internal/entities/command_tags.go
internal/entities/command_tags_test.go

First pass at some command cleanup for the `entities` package related to #110 
* Renames all the variables to standards we discussed
* Adds a middle command `tags` which I'm not sure I love TBH (or could be `tag`)
```bash
$ ./bin/darwin/newrelic entity
Subcommands to interact with New Relic entities
Usage:
newrelic entity [command]
Available Commands:
search      Search for New Relic entities
tags        Manage tags on New Relic entities
Flags:
-h, --help   help for entity
Use "newrelic entity [command] --help" for more information about a command.
FATA[0000] subcommand is required
```
```
$ ./bin/darwin/newrelic entity search -h
Search for New Relic entities
The search command performs a search for New Relic entities. Optionally, you can
provide additional search flags as filters to …
```

Change command to entity, rename commands

---

go.mod
go.sum
internal/apm/command.go
internal/apm/command_application.go
internal/apm/command_deployment.go
internal/apm/command_deployment_test.go

* Update newrelic-client-go to get more metatdata on entities (and fix missing applicationId on apm/application
* Moved AccountID and ApplicationID to the root `apm` command as persistent flags for sub-commands.
* Fix `apm application search` to accept accountId as a filter
* Fix `apm application search` to accept a GUID

Update newrelic-client-go 0.16.0

---

cmd/newrelic/main.go
go.mod
go.sum
internal/client/client.go
internal/nerdgraph/command.go
internal/workload/command.go
internal/workload/command_test.go
internal/workload/command_workload.go
internal/workload/command_workload_test.go

This PR adds workloads to the CLI.
Output is prettified and sent to stdout for get, list, create, and duplicate methods only.  Otherwise success/failure is indicated on stderr and command exit status.

feat(workloads): add a workloads subcommand

---

go.mod
go.sum
internal/workload/command_workload.go

This PR updates newrelic-client-go to v0.19.0.

chore(newrelic): update newrelic-client-go to v0.19.0

---

internal/client/client.go
internal/client/client_integration_test.go

Add logic in the overrides function to ensure the regions are valid before continuing.  Region attempt order is ENV, Profile, Default with error messages on every failure.
This should resolve #101

chore(client): Sanitize Region override

---

go.mod
internal/credentials/profiles.go
internal/credentials/profiles_integration_test.go

Region is still broken when stored in lower-case (nr1 format) with a confusing error:
`FATAL[] unable to create New Relic client with error: unknown region: us, using default: US`
This adds a custom decoder so when the profiles are loaded, we run the region through `region.Parse` to validate them.

Region fix (again)

---

.chglog/CHANGELOG.tpl.md
build/document.mk
build/release.mk

goreleaser supports (though not well documented) custom release notes.  Since we aren't using the build-in changelog we have not had release notes, and have had to manually add them.  The changes that behavior to automatically generate notes based on the last tag, and use them when goreleaser pushes a new release.

Custom release note generation

---

cmd/newrelic/command.go

Every release we regenerate the docs in Markdown and most of the changes are a date stamp.  We should just leave that off.

chore(newrelic): Disable date printing on generated documentation

---

cmd/newrelic/command.go
go.mod
internal/apm/command_application.go
internal/apm/command_deployment.go
internal/entities/command_search.go
internal/entities/command_tags.go
internal/nerdgraph/command_query.go
internal/nerdstorage/command_collection.go
internal/nerdstorage/command_document.go
internal/output/config.go
internal/output/json.go
internal/output/output.go
internal/output/print.go
internal/output/yaml.go
internal/workload/command_workload.go

Previously, we had one method of output: Pretty Print JSON.  This is fine for folks that are interacting with the CLI, but more options would be better.
This PR:
* Consolidates all output to a new `output` package (creative right?)
* Adds support for YAML output.  Since the data is structured, it was a logical choice though not sure it will get much use
* Adds `--format (json|yaml)` flag that allow runtime changes of the format
* Enables plain / compact output of JSON via `--plain` flag

Output refactor + formatting options

---

.goreleaser.yml

goreleaser was configured to run `make clean` which breaks other make tasks run prior to goreleaser being called in `make release-publish`.  This removes the pre-hook, as the expected work-flow is to always use make targets.

Fix: Goreleaser Release Notes

---

build/release.mk

Currently `make snapshot` misses all the other make targets that `make release-publish` does, which means it's not a valid local test.

Fix: increase coverage of make snapshot

---

.goreleaser.yml
README.md

Resolves: #167 
This PR adds Scoop to the GoReleaser, which will generate and publish a Scoop App Manifest into our repository. Windows users should be able to install the CLI via `scoop`.
The README has also been updated with installation instructions for Scoop.
Installing with Scoop:
```bash
scoop bucket add newrelic-cli https://github.com/newrelic/newrelic-cli.git
scoop install newrelic-cli
```

feat(build): provide installation via Scoop (Windows)

---

README.md

Noticed that the OSS header was missing. Rather than open an issue, here's a PR.

docs: add the OSS category header

---

.goreleaser.yml
build/lint.mk

This reverts commit 25637ff24bfcddd0a14e51ddae6df4a827d21d4d.
This also updates the commit format for scoop.

chore(build): revert linter configuration for scoop

---

.github/workflows/release.yml
build/document.mk
build/release.mk

Github Actions do not have the entire log, so release note generation fails.

chore(build): Update GH Action to fix release notes

---

.github/renovate.json

Renovate seems to have stopped running `go mod tidy` and hasn't been updating our `go.sum` file. Hoping the [postUpdateOptions](https://docs.renovatebot.com/configuration-options/#postupdateoptions) config option fixes that.

chore(renovate): update the renovate config with postUpdateOptions

---

build/package/chocolatey/tools/VERIFICATION.txt
build/package/chocolatey/tools/chocolateyinstall.ps1

Related: #170
A Chocolately [reviewer has requested](https://chocolatey.org/packages/newrelic-cli/0.7.0) we remove unnecessary variables from the install script. 
2020.22.05 - Still awaiting response [here](https://chocolatey.org/packages/newrelic-cli/0.7.0)
2020.26.05 - Heard back. Made updates. Ready for review.

chore(chocolatey): remove unnecessary variables from ps1 install script

---

.github/renovate.json
CHANGELOG.md

- **build:** Docker makefile was missing binary name
- **build:** ignore Scoop commits during commit linting
- **chocolatey:** fix typo in chocolatey verfication.txt

chore(changelog): Update CHANGELOG for v0.8.5

---

internal/config/config.go
internal/config/config_integration_test.go
internal/config/table_renderer.go
internal/config/ternary.go
internal/config/ternary_test.go

We want to ship features that have been announced, but not GA in a way that is not confusing to our users.  To do so, we will add a config option to display the non-GA features within the CLI if a user chooses to do so.  Otherwise hide them by default.
This resolves #274

[feat] Add pre-release config option

---

.goreleaser.yml

This PR fixes the Scoop commit message author email, which was being set as `<{{ .Env.DEV_TOOLKIT_EMAIL }}>`.

fix(scoop): fix bot email address

---

README.md

It looks like the Building section was copied from `newrelic-client-go`. It incorrectly stated that the package doesn't create any usable artifacts.

docs(README): Correct Building section

---

build/lint.mk
build/test.mk
cmd/newrelic/main.go
go.mod
go.sum
internal/reporting/command.go
internal/reporting/command_junit.go
internal/reporting/command_junit_test.go
internal/reporting/command_test.go
tools.go

Add JUnit reporting to NRDB via the `newrelic reporting junit` command.
This PR also adds JUnit test output to the build pipeline, so it can be used for testing of this functionality.  
```
./bin/darwin/newrelic reporting junit --accountId 2520528 --path ./coverage/integration.xml
```

feat(reporting): add junit reporting

---

.tutone.yml
internal/nerdgraph/command_mutation.go
templates/command.go.tmpl

Resolves: #375 
This PR introduces our first command to be created with code generation.
```
make compile-only
```
```
./bin/darwin/newrelic nerdgraph mutation alertsPolicyCreate
```
Depends on: https://github.com/newrelic/tutone/pull/78

feat(nerdgraph): implement tutone-generated mutation command alertsPolicyCreate

---

go.mod
go.sum
internal/entities/command_tags.go
internal/pipe/pipe.go
internal/pipe/pipe_test.go

This PR adds a pipe module to read stdin for piping input to commands, allowing each command
be piped to the next. I've also implemented this pipe logic for one command, the `entity tags get`
command. You can try this functionality by running:
`newrelic entity search --name [app name] | newrelic entity tags get`
Currently the above action only returns tags for the first entity found. Work has to be done in 
newrelic-client-go to add bulk queries to the API. Specifically for this tag query, something like this query needs 
to be added (this is incorrect, working on it in a different repo):
```
query($guids:[EntityGuid]!) {
actor {
entities(guids: $guids) {
tags {
values
key
}
}
}
}
}
```
For the entity tag command alone, nrClient.Entities.ListTags, nrClient.Entities.DeleteTags, …

feat(release): Issue #45 add support for command chaining

---

go.mod
go.sum
internal/entities/command_tags.go
internal/pipe/pipe.go
internal/pipe/pipe_test.go

This PR adds utility methods and logic to read stdin
for details needed in commands, allowing each command
ouput to be piped to the next command
https://github.com/newrelic/newrelic-cli/issues/45
refactor(release): WIP clean up logic in init function
This commit refactors the init logic to be cleaner, handle
more flags, and prepare for bulk actions
feat(release): WIP collect values from multiple results and add tests
This commit adds more testing and allows reading values from multiple
results
refactor(release): WIP create pipe module
This commit pulls the pipe input logic out of the utils module
and into a new pipe module. It also abstracts the PipeInput map
from other modules.
feat(release): make newrelic entity tags get cmd take stdin
This commit is the last step I can take towards …

feat(release): #45 add support for command chaining

---

internal/install/install.go

Currently, we execute all the tasks in the file you pass, even if you've used a 'named' task to encapsulate your other tasks.
For example:
```yaml
tasks:
parent_task:
cmds:
- task: named_task_1
- task: named_task_2
named_task_1:
cmds:
- echo "Hello world 1"
named_task_2:
cmds:
- echo "Hello world 2"
```
Without this change, we will run the `parent_task` which runs `named_task_1` and `named_task_2` and then it will individually run `named_task_1` and `named_task_2` again.
With this change, we will need to update the yaml to look like:
```yaml
tasks:
default:
cmds:
- task: named_task_1
- task: named_task_2
named_task_1:
cmds:
- echo "Hello world 1"
named_task_2:
cmds:
- echo "Hello world 2"
```
If `ParseV3` is not passed a specifically named task, it will attempt to (only) run a task named …

fix: duplicitous task running

---

.github/workflows/changelog.yml
.github/workflows/compile.yml
.github/workflows/release.yml
.github/workflows/snapshot.yml
.github/workflows/test.yml

Without this change, the deprecation is preventing the jobs with add-path from
executing properly.  Here we update the setup and install of the workflows and
allow the PATH handling to be done by setup-go.

chore(build): update workflows to avoid deprecated add-path

---

internal/install/execution/go_task_recipe_executor.go
internal/install/execution/go_task_recipe_executor_test.go
internal/install/execution/mock_recipe_executor.go
internal/install/execution/recipe_executor.go
internal/install/recipe_installer.go
internal/install/recipes/service_recipe_fetcher.go
internal/install/types/recipe.go

Without this change, the UX for a user is less than ideal while prompting for
input vars on a given recipe.  Currently, the spinner for the task continues to
spin even while the process waits for input from the user.  To avoid confusing
the users, this work breaks the Execute() phase of a recipe execution into two
steps, Preapre() and Execute() to allow the process to gather all required input
up front and build the set of variables to be passed in to the Execute() phase.
This allows only the Execute() phase to show the spinner, while the Prepare()
phase does not.

refactor(install): avoid spinner while prompting

---

internal/install/command.go

Without this change, the client is not aware of the user's desires, and the log
level is confined to the logged messages in the CLI code.  Here we use a new
method on the client to set the log level when debug or trace are requested by
the user.

fix(logging): set client logger level

---

go.sum
internal/install/discovery/psutil_discoverer.go
internal/install/discovery/psutil_discoverer_test.go
internal/install/types/discovery_manifest.go

This PR uses reflection over generated types to ensure that we are not sending invalid values for `platform` or `platformFamily` when retrieving recommendations from the recipe service.
cc @jbeveland27  @michaelkro

chore(install): add validation and filtering for platform and platform family

---

internal/install/recipes/service_recipe_fetcher.go
internal/install/recipes/service_recipe_fetcher_test.go

Without this change, the duplicate fix in 9ee4a93 is too aggressive in removing
the duplicates.  In the case where we fetch recipes, we want all results so that
we are able to effectively determine all of the process filters regardless of
the name of the recipe.  Here we shift that duplicate avoidance to the
FetchRecommendations call instead, since we only want to remove the duplicates
in the case the recipe service sends back a duplicate when we are looking for
recommendations.

fix(install): avoid duplicate results when fetching recommendations

---

internal/install/execution/nerdstorage_status_reporter.go
internal/install/validation/polling_recipe_validator.go

Without this change, the GUID is not returned from a logs validation query due
to the different format.  The standard case seems to use entityGuid, while logs
uses entity.guids.  Here we ensure we capture both cases for the return.

fix(install): capture guid from validation when alternate format

---

internal/install/execution/mock_status_reporter.go
internal/install/execution/nerdstorage_status_reporter.go
internal/install/execution/status.go
internal/install/execution/status_reporter.go
internal/install/execution/terminal_reporter.go
internal/install/recipe_installer.go
internal/install/recipe_installer_test.go
internal/install/recipes/service_recipe_fetcher.go
internal/install/types/recipe.go

Currently, all the recipes up to this point have been of type HOST.  Here we
seek to report on any non-HOST recipes, but only take the install actions when
the type is a HOST.  This work plumbs through the Recommended() methods through
the reporters and ensures that we only attempt to install recipes that are of
type HOST, regardless of what was returned from the recommendations endpoint.

chore(install): implement recommended recipe reporting

---

internal/install/execution/go_task_recipe_executor.go
internal/install/recipe_installer.go
internal/install/types/errors.go
internal/utils/utils.go

At any phase during the install command (prompts, execution, validation), if ctrl-c is pressed the command should cease execution without attempting to do anything else.
In the case of third-party libraries, cancelled contexts are handled from within the libraries and allow for executing IO-blocking procedures with a passed context.
All we need to do is handle the error that comes back from those libraries appropriately.  In the case of the OHI execution loop, we opt to try the next recipe if the current one fails - this leads to unexpected behavior when ctrl-c is the cause of the error.
This PR makes it so that we will try the next recipe, but only if the error that comes back from the various 3rd party libraries was not generated by a context cancellation.

fix(install): make ctrl-c exit reliably

---

internal/install/command.go
internal/install/install_context.go
internal/install/install_context_test.go
internal/install/recipe_installer.go
internal/install/recipe_installer_test.go
internal/install/test_command.go
internal/install/ux/mock_prompter.go

This change means that the infra agent will be installed each time, unless the
user supplies a recipe by name or by URL.

chore(install): remove the option to skip infra install

---

internal/install/command.go

Removing pre-release designation for the `install` command to prepare for GA.

chore(install): remove pre-release designation

---

README.md

The warning isn't needed anymore. Ref: #702

Fix: removed outdated warning for Chocolatey

---

internal/output/output.go

This will avoid the 70+ file PR when generating docs during the release process.

chore: order output formats deterministically in docs

---

internal/install/execution/install_status.go
internal/install/execution/mock_status_reporter.go
internal/install/execution/nerdstorage_status_reporter.go
internal/install/execution/nerdstorage_status_reporter_unit_test.go
internal/install/execution/status_subscriber.go
internal/install/execution/terminal_reporter.go
internal/install/recipe_installer.go
internal/install/recipe_installer_test.go
internal/install/types/discovery_manifest.go

This PR introduces host discovery info to nerdstorage payloads during the install process.
cc @devfreddy @jbeveland27 
An end-to-end flow should show no regressions, and retrieving the Nerdstorage documents for user and entity scope post-install should show the new information.

chore(install): add host discovery info to nerstorage payloads

---

internal/install/recipe_installer_guided.go
internal/install/recipe_installer_test.go

Related: [newrelic/open-install-library #293](https://github.com/newrelic/open-install-library/pull/293)

fix(install): discovered log files needs to be a string to work within our recipe

---

internal/config/logging.go
internal/install/command.go

fixes: #803
Without this change, we initialize the file logger even when we might not intend
to.  Here we ensure that the file logger is only initialized during execution of
the install command.

fix: init the file logger only for the install command

---

scripts/install.sh

Need to use `uname -m` for arm7 on raspberry pi

fix(install): use machine name for arm7

---

internal/install/execution/install_status.go
internal/install/execution/install_status_test.go
internal/install/execution/mock_success_link_generator.go
internal/install/execution/nerdstorage_status_reporter_integration_test.go
internal/install/execution/nerdstorage_status_reporter_unit_test.go
internal/install/execution/success_link_generator.go
internal/install/execution/terminal_reporter.go
internal/install/execution/terminal_reporter_test.go
internal/install/recipe_installer.go
internal/install/recipe_installer_test.go
internal/install/recipes/service_recipe_fetcher.go
internal/install/scenario_builder.go

Currently we have very similar logic on the frontend as we do in the CLI. This PR ensures a backwards compatible way to provide a redirect URL for the frontend to use when generating the link used for "See Your Data" upon a successful installation.

chore(install): provide redirect URL on nerdstorage doc for frontend to use

---

cmd/newrelic/command.go
cmd/newrelic/command_integration_test.go
go.mod
go.sum
internal/diagnose/command_validate.go
internal/diagnose/config_validator.go
internal/install/discovery/noop_process_filterer.go
internal/install/execution/go_task_recipe_executor_test.go
internal/install/recipe_installer.go
internal/install/recipes/recipe_file.go
internal/install/types/errors.go
internal/install/validation/mock_recipe_validator.go
internal/install/validation/polling_recipe_validator.go
internal/install/validation/polling_recipe_validator_test.go
internal/install/validation/recipe_validator.go
internal/utils/nrdb_client.go
internal/utils/validation/polling_nrql_validator.go

Depends on newrelic/newrelic-client-go#724.
Run cold start command from a fresh VM without the CLI installed.  Once it is finished:
```
sudo newrelic profile list --show-keys
```
You should see that the Insights insert key should have been retrieved and populated when the profile was created.  
Then,
```
sudo newrelic diagnose validate
```
The validation process will kick off and report success once it finds the event.  To locate the diagnostic event manually, run the following query:
```
SELECT * FROM NrIntegrationError WHERE purpose = 'New Relic CLI configuration validation'
```
- Improve success and error messages
- Improve `profile add` command to make use of the key location functionality

(feat): validate CLI config

---

internal/install/execution/go_task_recipe_executor.go
internal/install/execution/install_status.go
internal/install/execution/line_capture_buffer.go
internal/install/execution/line_capture_buffer_test.go
internal/install/execution/status_subscriber.go
internal/install/recipe_installer.go
internal/install/scenario_builder.go
internal/install/types/errors.go
test/recipes/testError.yaml

This PR has a few effects:
1. Removes a bunch of the noise from go-task errors
2. Appends the final line of stderr to the go-task error so that it will appear in the final FATAL message presented to the user
```
newrelic installTest -c test/recipes/testError.yaml
```
The `testError.yaml` file can be updated as desired to try various recipe invocation scenarios.
1. Removing the "noise" in the error also loses some of the context about which sub-task in the recipe the error originated from. (e.g. `task: Failed to run task "default": task: Failed to run task "execute":`) Is this acceptable?
1. Errors will show up in the `FATAL` message if:
1. The convention `echo -e "error message" >&2` is used directly in the recipe.  (`echo -e "eror message" > /dev/null` **will not** work since that routes …

chore(install): make go-task errors nicer

---

internal/install/execution/install_status.go
internal/install/execution/status_subscriber.go
internal/install/recipe_installer.go
internal/install/types/discovery_manifest_test.go
internal/install/types/errors.go
internal/install/types/errors_test.go

Run a guided install with this code & force an error.  (I've done this by using the `-c` option against a recipe that isn't compatible with the platform I'm on).  Look in Tessen for the error event and check that the `error_task_path` attribute contains the task the error occurred in:
```
FROM TessenAction SELECT error_task_path where email = 'your_email@newrelic.com' and category = 'GuidedInstall' and error_message is NOT NULL
```

fix(install): fix task path field name and support nested tasks

---

internal/install/types/recipe.go
internal/install/types/recipe_test.go

This PR updates the `OpenInstallationRecipe` custom `UnmarshalYAML()` method to handle converting multiple types to a string.
I ran into panic errors when unmarshaling the elasticsearch recipe via `--recipePath` because the input variables of the port and SSL checks are `int` and `bool` respectively. The `toStringByFieldName()` helper function needed to be updated to handle these scenarios and others like it.

fix(install): UnmarshalYAML toStringByFieldName() should handle multiple types when converting interface 

---

scripts/install.sh

The installation on aarch64 did not work because uname was missing the -m parameter.
Also the release artifact for ARM64 is called arm64 and not aarch64.
I corrected both and tested it on a Ubuntu 20.04 installation on a Raspberry Pi 4B.

Update install.sh to work on ARM64

---

cmd/newrelic/command.go
cmd/newrelic/command_integration_test.go
go.mod
go.sum
internal/diagnose/config_validator.go
internal/install/execution/nerdstorage_status_reporter_integration_test.go
internal/install/recipe_installer.go
internal/utils/retry.go
internal/utils/retry_test.go
internal/workload/command_workload.go

- update `newrelic-client-go` to v0.60.1, including generated `workload` types
- make `utils.Retry` context-aware
- use context-aware methods during config initialization, config validation, and a few other locations

chore: update client to v0.60.1, add context to config validation

---

scripts/release.sh

We used to sort by tag, however git-chglog requires a flag to sort by semver tag now. This PR gets our CHANGELOG sorted properly.

chore(build): sort changelog by tag instead of date

---

.github/workflows/release.yml
.goreleaser.yml

This PR uploads release artifacts to the `nr-downloads-main` bucket in S3 so that they can be made available on download.newrelic.com. 
~We will need to get a service user provisioned and set the `AWS_AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` variables in this repository before using this updated release pipeline.~
A service user has been provisioned and the env vars `AWS_AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` have now been set in this repository.
This was tested on my [fork](https://github.com/ctrombley/newrelic-cli) in a messy [pull request](https://github.com/ctrombley/newrelic-cli/pull/1).  Once the pipeline was successful there, the relevant parts were copied upstream to create this PR.

feat: publish release artifacts to S3

---

cmd/newrelic/main.go
internal/integrations/command.go
internal/integrations/command_config.go
internal/integrations/command_test.go
internal/integrations/model.go
internal/integrations/utils.go
internal/integrations/utils_test.go

We wrote a small helper in order to simplify the migration between V3 and V4 configuration of onHost integration.
Both the users and the support could be interested in this tool since given a V3 definition and configuration generates a working V4 configuration file.
I was not 100% sure that this is the right place for the new functionality or if it is better to place it under the `agent` command.

Feat command to migrate configuration file v3->v4

---

.github/workflows/release.yml
build/chocolatey.mk

Seems like changing directory from within the make target was [causing problems in Github actions](https://github.com/newrelic/newrelic-cli/runs/3489733702?check_suite_focus=true):
```
Run make chocolatey-publish
=== newrelic-cli === [ chocolatey-build ]: publishing chocolatey package
sed: can't read : No such file or directory
```
Also, this now takes a dependency on the MSI in S3, so it needs to be moved after that artifact's publish step.

fix: get chocolatey publish pipeline working

---

internal/cli/version.go

The GitHub Action `battila7/get-version-action` `output` value is a version string that contains an extra empty space which is causing issues with that check. This PR trims the extra empty space around the version string to get this working again.

fix(install): add defensive code to trim whitespace from version string so version check works again

---

go.mod
go.sum
internal/apm/command_application.go
internal/entities/command_tags.go
internal/install/execution/installevents_reporter.go
internal/install/execution/nerdstorage_status_reporter_integration_test.go
internal/workload/command_workload.go

newrelic-client-go v0.63.0 has a breaking change, so update all references of `entities.EntityGUID` to `common.EntityGUID`

chore(deps): Update github.com/newrelic/newrelic-client-go v0.63.0

---

.github/workflows/e2e-eu.yml
.github/workflows/e2e.yml
.github/workflows/release.yml
.github/workflows/test.yml
scripts/release.sh

🤖 **New releases will be created via the GitHub Actions UI** 🤖 
**Checklist**

chore(release): use GitHub Actions UI to trigger release workflow via `workflow_dispatch` event 

---

README.md

fix(readme): use GitHub URL for downloading latest release binaries

---

scripts/install.sh

Printing out the name of the machine hardware via `uname -m` on the new M1 chip MacBooks outputs `arm64`, thus we need to include a check for this in the install script.
FIxes #1250

fix(install): allow CLI installation on new Macs w/ M1 chip

---

internal/install/ux/spinner_progress_indicator.go

The PR improves the legibility and UX of the highlighted install status text by adding padding (whitespace) to the highlighted output (see screenshots).

feat(install): add padding to highlighted text for better legibility

---

go.mod
go.sum
internal/install/execution/recipe_var_provider.go
internal/install/execution/recipe_var_provider_test.go

This PR considers both `NRIA_CUSTOM_ATTRIBUTES` and `NRIA_PASSTHROUGH_ENVIRONMENT` envars.  If either envar is present on the command line when running an install, they are parsed/added to the recipe context as yaml 'chunks'.  This allows us to update the recipe yaml to check for `{{.NRIA_CUSTOM_ATTRIBUTES}}` or `{{.NRIA_PASSTHROUGH_ENVIRONMENT}}` and append their values to `newrelic-infra.yml` without needing to transform data in bash.
Example output from a test EC2 instance - comparing `env` output to  `echo "{{.NRIA_CUSTOM_ATTRIBUTES}}"` and `echo "{{.NRIA_PASSTHROUGH_ENVIRONMENT}}"`
```
DEBUG NRIA_CUSTOM_ATTRIBUTES={"customAttribute_1":"SOME_ATTRIBUTE_YAY","customAttribute_2": "SOME_ATTRIBUTE_2"} 
DEBUG NRIA_PASSTHROUGH_ENVIRONMENT=one,two,three,fourteen 
DEBUG custom_attributes: …
```

feat(envars-to-recipe):  Passing envars as yaml to recipe context

---

internal/install/execution/recipe_var_provider.go
internal/install/execution/recipe_var_provider_test.go

Cuts down on verbose warning logs; still leaving length check within transformation methods

chore(envars): check envar length prior to attempting yaml transformation

---

internal/install/execution/recipe_var_provider.go
internal/install/execution/recipe_var_provider_test.go

Was logging as `warning`s which show in the CLI output in normal, non-debug mode.  Reduced to `debug` and added key of envar that is problematic
`DEBUG Invalid json passed in NRIA_CUSTOM_ATTRIBUTES: {"some-valid":"json","valid":false,"awefaewnte1} `

Update logging for envar-to-yaml transformers

---

.github/workflows/release.yml
build/package/msi/NewRelicCLIInstaller/SignMSI.cmd
build/package/msi/NewRelicCLIInstaller/SignPS1.cmd

The `.msi` file is signed with SHA1; `.ps1` file is not signed. Trying to fix this last one and improving by using SHA256.

chore(release): test ps1 signing and using sha256

---

.github/workflows/release.yml

Workflow ps1 file signing path was correct. Reverting change.

chore(release): revert ps1 file workflow signing path change

---

.github/workflows/release.yml

As I do not see how to sign the `newrelic.exe` for Windows from within `goreleaser` before zipping it, I am trying this approach:
- After `make release-publish` runs, delete the `dist/newrelic-cli_<VERSION>_Windows_x86_64.zip` archive that is produced by goreleaser.
- Then, get the version tag and generate that same zip `dist/newrelic-cli_<VERSION>_Windows_x86_64.zip` in a new job step via a linux `zip` command. By this time, the `newrelic.exe` that is compressed into that zip file is (should be) already signed.
- Finally, this file should be picked up by the later step that uploads everything to S3/Github (need to confirm).

chore(release): re-do windows zip

---

README.md

Seems this github action does not exist anymore, and it looks scary when you open the README

chore(docs): removed old security scan image

---

internal/client/client.go

Reported that user had a default profile configured in `$HOME/.newrelic/` which _should_ have been considered when running install without specifying envars or `--profile <some-profile-name>`
Turns out a side-effect to asserting a valid profile is we rebuild a client object with an empty profile reference.  This causes a lookup for api and license keys to fail/remove what was there.
Solution is to reuse existing client object for install commands if no profile name is provided (presence of a non-nil client object is part of this commands `PreRun:` hook

fix(default config): comment out fetching of license key

---

internal/install/recipes/local_recipe_fetcher_test.go

This PR is to help the TDP team complete the infra agent's PGP key path update. Original PR is: https://github.com/newrelic/newrelic-cli/pull/1346 and credits to @rubenruizdegauna

chore(infra): infra agent gpg key path update

---

internal/utils/command_yq.go
internal/utils/command_yq_test.go
internal/utils/yq/error.go
internal/utils/yq/inputs.go
internal/utils/yq/marshaler.go
internal/utils/yq/yaml.go

The `utils` subcommand was added awhile back (a few years at this point) to give a place where we could expose various utility functions. Among other things, this is useful for embedding utils in the CLI vs relying on them being available on hosts when running recipes.
The `newrelic utils jq` command was added by utilizing [gojq](https://github.com/itchyny/gojq) as a library. `gojq` itself has CLI support for a variety of flags that are intentionally not exposed (see [this issue](https://github.com/itchyny/gojq/issues/181#issuecomment-1221449914) for ref). However, there's nothing really holding us back from adopting the internal package code to expose some additional functionality for ourselves.
This PR adds support for [yq](https://github.com/mikefarah/yq)-like functionality, which is …

feat(utils): add yq utility for embedded yaml editing

---

README.md

The link previously referenced a github.io link that's currently a 404 (and has been for a while). I couldn't find a mirror of this, so linking to https://developer.newrelic.com seems like the best alternative.

README: Update "developer toolkit" link to developers.newrelic.com

---

internal/install/execution/go_task_recipe_executor.go
internal/install/execution/go_task_recipe_executor_test.go
internal/install/execution/line_capture_buffer.go
internal/install/execution/line_capture_buffer_test.go
internal/install/execution/mock_recipe_executor.go
internal/install/execution/mock_recipe_log_forwarder.go
internal/install/execution/output_parser.go
internal/install/execution/output_parser_test.go
internal/install/execution/recipe_executor.go
internal/install/execution/recipe_log_forwarder.go
internal/install/execution/recipe_log_forwarder_test.go
internal/install/execution/sh_recipe_executor.go
internal/install/recipe_install_builder.go
internal/install/recipe_installer.go

Removed capturing CLI output in temp file in favor of storing in memory.  This removes unnecessary file handling/cleanup that surfaced some issues with our windows infra recipes last week

feat(logs): removed usage of temp file for log output

---

internal/install/execution/go_task_recipe_executor.go
internal/install/execution/go_task_recipe_executor_test.go
internal/install/execution/installevents_reporter_test.go

In an effort to cleanup metadata use sourced from our recipes, make sure we clear out any existing metadata if none is available.  The recipe execution context where output is stored is shared across all recipe executions...we've always overwritten prior metadata if subsequent recipe metadata was present, but if not, the original metadata was attached to all subsequent recipe statuses being reported

chore(metadata): only send metadata belonging to recipe

---

scripts/install.sh

If it does not exist, creates default `DESTDIR` path (`/usr/local/bin`) where the `install.sh` script moves the downloaded `newrelic` binary to. Corrects `not a directory` error in MacOS.

fix(scripts): install dir check

---

go.mod
go.sum

This client upgrade includes adding the ability to prepend additional requesting service names in our request header.
Related to: [newrelic-client-go #985](https://github.com/newrelic/newrelic-client-go/pull/985)

chore(deps): upgrade newrelic-client-go to v2.12.0

---

internal/install/execution/recipe_var_provider.go
internal/install/execution/recipe_var_provider_test.go
internal/utils/utils_test.go

Passing all `--tag` arguments through to open-install-library recipe's context via `NEW_RELIC_CLI_TAGS` variable.
key:values will be semicolon delimited i.e. `key:value;another_key:another_value`

feat(tags): propagate cli tags to recipes via NEW_RELIC_CLI_TAGS

---

scripts/install.ps1
scripts/install.sh

For `install.sh` and `install.ps1`, check for connectivity to `https://download.newrelic.com` and provide a helpful message if unable to connect.
For `install.ps1`, adds a proxy to the requesting `WebClient` via the optional environment variable `HTTPS_PROXY`, which will enable setting a proxy for the CLI download.

Improve proxy support for install scripts

---

internal/install/execution/platform_link_generator.go
internal/install/execution/platform_link_generator_test.go

Adds `installId` to the platform redirect links generated by the CLI. This will allow the browser UI to fetch historic data for the related install statuses and recipes.

feat(NR-94773): Add `installId` to platform links

---

internal/install/command.go
internal/install/recipe_installer.go

Moves the call to `checkNetwork()` from inside the installer to before fetching the license key. Also adds more descriptive and helpful error messages if `checkNetwork()` fails.

chore(install): Improve network error detection and messaging

---

internal/install/execution/platform_link_generator.go

Changes url param `installId` to `installIds` to align with UI expectations. The UI is already compatible with this so it is not a breaking change.
I tested by compiling manually and running a partial guided install on an EC2 instance. I then followed the link and confirmed:
1. The install status rehydrated correctly
2. The url param contained `installIds` not `installId`

feat(install): Pluralize installId url param

---

build/compile.mk
internal/install/execution/go_task_recipe_executor.go

Problem: Unable to write to metadata file with window recipe due to it kept open by CLI
Fix: Close metadata file after creating
Add a new compile option for Windows x86

fix: Close metadata file and prevent file lock during recipe write

---

internal/utils/terraform/dashboard.go

This PR addresses [NR-108075](https://issues.newrelic.com/browse/NR-108075), comprising of the following changes - 
- Addition of a condition in the dashboard utility in the CLI to convert the given Dashboard JSON to HCL, to receive the newly added attribute, `zero` (in newrelic-client-go) as `y_axis_left_zero` in HCL, to be used in Terraform.
Linked changes in dependencies
**terraform-provider-newrelic** : [PR](https://github.com/newrelic/terraform-provider-newrelic/pull/2329)
**newrelic-client-go** : [PR](https://github.com/newrelic/newrelic-client-go/pull/1023)

fix(dashboard): addition of 'zero' to the dashboard HCL parser utility

---

internal/install/execution/nerdstorage_status_reporter.go
internal/install/execution/nerdstorage_status_reporter_integration_test.go
internal/install/execution/nerdstorage_status_reporter_unit_test.go

Removes writes to account- and user-scoped NerdStorage from the install status reporter. The status reporter should only write to entity scope.
New Relic UI no longer depends on the `openInstallLibrary` collection, except for entity-scoped NerdStorage data.

chore(install): Remove user/account NerdStorage writes

---

internal/client/client.go
internal/client/client_test.go
internal/config/config.go
internal/diagnose/config_validator.go
internal/install/command.go
internal/install/command_test.go
internal/install/license_key_fetcher.go
internal/install/license_key_fetcher_test.go
internal/install/recipe_installer.go
internal/profile/command.go

To account for some license key generation lag with new customers, we are increasing the request retry timeout to ensure we can fetch the newly generated license key for new customers.
The changes in this PR are intended to be scoped to increasing the timeout only for fetching the license key.

chore(install): increase license key fetch retry timeout to 5 minutes

---

.goreleaser.yml

Re-enabling Snap and Docker push now that we were able to add our Docker Hub service account (nrdevelopertoolkit) back to the `newrelic` org in Docker Hub. Credentials should be restored and pushing new releases to Docker Hub should work again.

chore(release): re-enable snap and docker push on release

---

internal/install/execution/terminal_reporter.go
internal/install/execution/terminal_reporter_test.go
internal/install/recipe_install_builder.go
internal/install/recipe_installer.go
internal/install/recipe_installer_test.go

Summary: Node agent prompt the user if they want to install during installation. If the user answers no, the install recipe will cancel out. CLI is currently not recording the cancel status for this event.
Fix: Report cancels the event for the recipe when they cancel inside recipe install.
Also, the terminal reporter does not print a summary if there are any recipes that are canceled. Updated to output install result even if there are some recipe that was canceled.

fix(install): Incorrect final recipe status if cancel during target install

---

internal/install/command.go
internal/install/execution/install_status.go
internal/install/execution/install_status_test.go
internal/install/execution/segment_report_test.go
internal/install/execution/segment_reporter.go

1. The complete count for Segment reporter reports an incorrect count since the detected status gets overwritten by other status, added a new slice to track detected and unsupported status.
2.  fix nil exception when local debugging without segment key file by returning no-op instead of nil

fix(install): Segment complete report and nil error when segment file missing

---

.github/workflows/release-homebrew.yml
.github/workflows/release-publish-windows.yml
.github/workflows/release-windows-installer.yml

This PR is just to add the new release workflow files. A follow-up PR will created to wire them up.
Note: These new files are not wired up and do not affect our release workflow until the follow-up PR is merged.

chore(release): create separate release workflows for post-release jobs

---

docs/cli/newrelic_nrql_droprules.md
internal/nrql/command_droprules.go
internal/nrql/command_droprules_test.go

Addition of a command to the CLI, `newrelic nrql droprules` to fetch droprules.
Arguments:
`--limit` to specify the number of rules to be printed, that defaults to 10

fix(nrql): addition of a command to retrieve nrql droprules

---

go.mod
go.sum
internal/entities/command_deployment.go
internal/entities/command_deployment_test.go

Adds the --attribute flag to the entity deployment create command, allowing the user to optionally add custom attributes to deployment markers.

feat: entity deployment customattributes

---

internal/entities/command_deployment.go
internal/entities/command_deployment_test.go

Allows users to have multiple --customAttribute flags

feat: custom attributes via stringslicevar

---

internal/install/recipe_install_builder.go
internal/install/recipe_installer.go
internal/install/recipe_installer_test.go
internal/install/recipes/recipe_builder.go
internal/install/recipes/recipe_detector.go
internal/install/recipes/recipe_detector_test.go
internal/install/types/install_context.go
internal/install/types/install_context_test.go
internal/install/types/recipe.go
internal/install/types/recipe_test.go
internal/install/types/types.go

- Allow new attribute `discoveryMode` in recipe pre-install section. 
- Accepts an one or many of possible value from [targeted, guided]
- If set to targeted, This will only detect the recipe if it's a target in the targeted install
- If Omit, default behavior is assume both (What we have today)

feat: Support Targeted Only Schema Update

---

go.mod
go.sum
internal/install/command.go
internal/install/command_test.go
internal/install/types/errors.go
internal/utils/utils.go
internal/utils/utils_test.go

This PR introduces some light input validation to capture when customers might be using the wrong API key format and/or an invalid New Relic region during agent installation. Messaging has also been updated in hopes of providing a more helpful, descriptive error message.

feat(install): validate user API key format

---

internal/install/recipe_installer.go

Makes validationNrql an additional method of validating OHI installation. The result is that the first successful method of validation will count as a successful installation. If all methods fail, the installation is considered to have failed.

fix: Validation nrql backup functionality

---

internal/install/command.go
internal/synthetics/command_batch_run.go
internal/synthetics/command_monitor_test.go

Duplicate events were tracked during the validateProfile( ), this PR remove the duplicate.
Also simplified the user facing error message to avoid confusing with license key, new user message below.
`FATAL 401 response returned: Invalid credentials provided. Missing API key or an invalid API key was provided. `

fix(install): remove duplicate tracking event and simplify error message

---

go.mod
go.sum
internal/entities/command_deployment.go
internal/entities/command_deployment_test.go

Supports JSON strings for `--customAttributes` for deployment markers. Ref: [NR-165686](https://new-relic.atlassian.net/browse/NR-165686).

feat(entities): Support custom attributes JSON

---

go.mod
go.sum
internal/entities/command_deployment.go
internal/entities/command_deployment_test.go

Supports JSON strings for `--customAttributes` in the `newrelic entity deployment create` command for deployment markers. Ref: [NR-165686](https://new-relic.atlassian.net/browse/NR-165686).
_*** Requires ***_ https://github.com/newrelic/newrelic-client-go/pull/1063 in a `newrelic-client-go` release > 2.22.0

feat(entities): Support custom attributes JSON (2)

---

internal/install/recipe_installer.go

Adds a `COMPLETE` install status event when CLI execution is user-canceled. Ref: [NR-173729](https://new-relic.atlassian.net/browse/NR-173729).

fix(install): Add complete install status for user-canceled execution

---

internal/install/recipes/bundler.go
internal/install/recipes/bundler_test.go

Adds the ability to skip `infrastructure-agent` as a dependency for OHIs if `super-agent` is targeted. If `super-agent` is no targeted, it will fall back to the original `infrastructure-agent` as their dependency.
Requires OIL changes: https://github.com/newrelic/open-install-library/pull/997
Ref: [NR-173011](https://new-relic.atlassian.net/browse/NR-173011)

feat(install): add super-agent as infra-agent substitute dependency

---

internal/synthetics/command_batch_run.go
internal/synthetics/command_batch_run_test.go

Updates default `isBlocking` behavior for continuous automated tests in CLI. Ref: [NR-182971](https://new-relic.atlassian.net/browse/NR-182971)

feat(synth): Update default isBlocking behavior

---

go.mod
go.sum

Replaces the `go-task/task` module with a forked version frozen at `v3.11.0`, i.e. the version we are currently using as of 1/18/24.
Link to the forked `go-task` repo in the `newrelic-forks` GH organization: https://github.com/newrelic-forks/task
Since `task` allows execution of shell commands on client machines, this will protect users in case a malicious third-party actor tampers with the dependency in the future.
https://new-relic.atlassian.net/browse/NR-178270

chore: Use a forked version of go-task for security

---

internal/synthetics/command_batch_run.go

Running `newrelic synthetics run --guid 1` causes the CLI to panic if NEW_RELIC_API_KEY and NEW_RELIC_LICENSE_KEY are unset:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc5a4b3]
goroutine 1 [running]:
github.com/newrelic/newrelic-cli/internal/synthetics.createAutomatedTestBatch({{{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...})
/Users/<USER>/<SOME_PATH>/newrelic-cli/internal/synthetics/command_batch_run.go:131 +0x93
github.com/newrelic/newrelic-cli/internal/synthetics.glob..func1(0x15e68e0?, {0xe77c09?, 0x2?, 0x2?})
/Users/<USER>/<SOME_PATH>/code/github.com/newrelic-cli/internal/synthetics/command_batch_run.go:57 +0x1a5
```
This PR adds a requirement for the client to be …

fix: Prevent panic in 'synthetics run' when client not initialized

---

build/release.mk

Try debugging release pipeline [error](https://github.com/newrelic/newrelic-cli/actions/runs/8069906445/job/22046132006#step:8:541) with GoReleaser:
```
release failed after 0s                  error=git is in a dirty stat
Please check in your pipeline what can be changing the following files:
M scripts/win_metadata_files_remove.sh
```

chore(build): Try enabling goreleaser debug cmd

---

.github/workflows/release.yml

As per [these lines](https://github.com/newrelic/newrelic-cli/actions/runs/8071438889/job/22051188377#step:8:317) in the debug log in the [publish release](https://github.com/newrelic/newrelic-cli/actions/runs/8071438889/job/22051188377) step, I think that the required `chmod +x` permissions for the scripts that need to deal with the Windows medata files, are being tracked by `git` as `modified` which in turn lets `goreleaser` show the[ initial error](https://github.com/newrelic/newrelic-cli/actions/runs/8069906445/job/22046132006#step:8:541) message: `git is in a dirty state`.
This PR adds `git config core.fileMode false` to the `release.yml` workflow, in an attempt to disable that tracking and let the release process to continue.

chore(build): Disable git tracking file permission changes

---

.gitignore

Trying to fix release pipeline [error](https://github.com/newrelic/newrelic-cli/actions/runs/8100446284/job/22138617304#step:8:899):
```
⨯ release failed after 0s                  error=git is in a dirty state
Please check in your pipeline what can be changing the following files:
?? cmd/newrelic/resource_windows.syso
?? cmd/newrelic/versioninfo.json
```

chore(release): Ignore windows metadata assets

---

tools/go.mod
tools/go.sum

Fixes
https://github.com/newrelic/newrelic-cli/security/dependabot/44
https://github.com/newrelic/newrelic-cli/security/dependabot/45
https://github.com/newrelic/newrelic-cli/security/dependabot/46

chore(deps): bump up deps docker/docker and protobuf, fix dependabot alerts 44, 45, 46

---

.github/workflows/release-windows-installer.yml

All changes handled in our gha workflow:`.github/workflows/release-windows-installer.yml`.  Since most of the public GHAs are written for linux distros, had to manually fetch the latest tag using `git`.
- Updated `Checkout code` step to pull branches/tags.  This provides the ability to fetch the latest tag in later steps
- Updated  `Compile installer` step to pass a `Version` parameter.  In testing, if this is an empty string, step will fail.  NOTE: tag v1.1.1 was created _after_ v1.2.3, proving that the chronologically newest version is ref'd

fix(msi): pass latest git tag as version

---

.github/scripts/main.js
.github/scripts/package.json
.github/workflows/e2e-dp-us.yml

Added a manually-dispatched GHA that leverages a deployer-platform stack in AWS to run regression tests against New Relic US domain. This can replace our existing e2e.yml within the next few days

feat(regression-tests): adding manually dispatched GHA for US end-to-end testing

---

.github/workflows/release-windows-installer.yml

Command obtained from [stack overflow](https://stackoverflow.com/questions/1404796/how-can-i-get-the-latest-tag-name-in-current-branch-in-git)
On my local machine
_fetch_
_describe tags_
_new describe tags_
It is worth noting that after some time, the original command seems to be working. It is unclear what has changed

chore(release): Get recent tag across all branches

---

internal/install/bundle_installer.go
internal/install/bundle_installer_test.go
internal/install/command.go
internal/install/recipe_installer.go
internal/install/recipe_installer_test.go
internal/install/recipes/bundle.go
internal/install/recipes/bundle_recipe.go
internal/install/recipes/bundle_test.go
internal/install/recipes/bundler.go
internal/install/recipes/bundler_test.go
internal/install/recipes/mock_process_evaluator.go
internal/install/recipes/process_evaluator.go
internal/install/types/recipe.go

This pull request uses the CLI functionality to detect the presence of the Super Agent on the host. If detected, it will install OHI with the Super Agent dependency, skipping the core bundle installation. If core recipes are targeted for installation, they will be unsupported since the Super Agent is already installed. (Associated PR: https://github.com/newrelic/open-install-library/pull/1072)

feat(super-agent): Skip core bundle if installed

---

internal/install/bundle_installer.go
internal/install/bundle_installer_test.go
internal/install/command.go
internal/install/recipe_installer.go
internal/install/recipe_installer_test.go
internal/install/recipes/bundle.go
internal/install/recipes/bundle_recipe.go
internal/install/recipes/bundle_test.go
internal/install/recipes/bundler.go
internal/install/recipes/bundler_test.go
internal/install/recipes/mock_process_evaluator.go
internal/install/recipes/process_evaluator.go
internal/install/types/recipe.go

Reverts newrelic/newrelic-cli#1604

feat(super-agent): revert changes from feat(super-agent): Skip core bundle if installed

---

.github/workflows/release.yml
.github/workflows/snapshot.yml

JIRA: https://new-relic.atlassian.net/browse/NR-272393
These modifications will initiate the CLI Docker image push during the release process rather than at the point of merging a PR into the main branch

feat: Publish CLI Docker image during release instead of during PR merge to main

---

internal/install/types/types.go

Adds Oracle Linux as a supported platform to allow for the installation of the Super Agent on Oracle Linux.

feat: Add supported platform oracle

---

internal/install/recipe_installer.go
internal/install/recipe_installer_test.go

Skips reporting a detected status for the infrastructure agent to the New Relic Installation UI, if the super agent is targeted.

fix: Skip detection reporting for infra if super

---

internal/install/validation/integration_validator.go

Adds an edge case for locally validating mongodb; by using `-short_running` we are able to execute the nri-mongodb3 integration once. The default behavior for nri-mongodb3 is to start a long running, background process.

feat: Mongodb local validation

---

internal/install/validation/integration_validator.go

Appends .exe to nri binaries if the operating system is Windows, thereby enabling local validation for Windows.

feat: Local validation windows

---

internal/install/command.go
internal/install/command_test.go
internal/utils/utils.go
internal/utils/utils_test.go

Refactors the validateProfile function and separates out a fetchLicenseKey function.
fetchLicenseKey will attempt to:
- Read a license key from the environment variable `NEW_RELIC_LICENSE_KEY`
- Read a license key from the active profile config
- Fetch a license key via the API
The license key will be fetched in that order; such that the environment variable is preferred over the active profile config, which is preferred over fetching via the API.
This allows users to use a license key of their choice (via `NEW_RELIC_LICENSE_KEY`) without the need to configure a profile.

feat: Env var license key

---

internal/install/command.go
internal/install/command_test.go

This PR will display an warning message through CLI, if `http proxy` is provided to the environment variable `HTTPSProxy`, and continue the installation process ignoring the proxy.
Ticket: https://new-relic.atlassian.net/browse/NR-306868
The warning message would look like this
Agent installation is successful providing the warning message, log record is attached here

fix(proxy-error): Show warning message for http proxy

---

scripts/install.ps1

Modifies the install.ps1 script to check for existing instances of the CLI. Removes all existing instances of the CLI before proceeding to the (re)installation.

fix: Uninstall previous cli version windows

---

internal/utils/validation/polling_nrql_validator.go

Fixes a fatal error that occurs when a user supplies only their license key. Fails silently (debug output) instead, so that the installation can continue.

fix: License key fatal error

---

go.mod
go.sum
internal/agent/command.go
internal/agent/command_test.go
internal/agent/version/version.go
internal/agent/version/version_test.go

Adds a sub-command to 'newrelic agent' called 'version', which displays the latest agent version for a given agent name.

feat: Agent version command

---

internal/install/execution/go_task_recipe_executor_test.go
internal/install/execution/line_capture_buffer.go
internal/install/execution/line_capture_buffer_test.go

Added logic to remove leading and trailing whitespace from error messages received from the OIL recipe. This addresses the issue of error messages being formatted incorrectly, often displaying only the exit status without the actual message content.
JIRA: https://new-relic.atlassian.net/browse/NR-329044
Before adding the logic
After adding the logic

chore: Resolved go task formatting inconsistency

---

internal/utils/terraform/dashboard.go

Problem Statement:
The problem at hand is to update the CLI dashboards utility which helps convert JSON dashboards into HCL-based dashboards (generating the newrelic_one_dashboard resource HCL configuration, from the JSON version of a dashboard) with the latest fields added to the Terraform resource, as these relatively new fields are unsupported by the CLI tool, owing to their absence in the parser of the tool, that needs an update
Solution :
schema of this CLI utility is updated with the latest fields updated in the newrelic_one_dashboard resource

fix(dashboard): Updated the Dashboard JSON to HCL Converter Utility with Latest Fields in the Resource

---

scripts/install.ps1

**Issue:-** Mentioned in the below jira ticket.
[Jira Ticket](https://new-relic.atlassian.net/browse/NR-372770)
**Fix:-** Escape square brackets in registry key paths in Windows installer script.
I tested it after the changes(Infrastructure Agent was installed successfully), please see below.
**Test Data:-**

fix(script): Escape square brackets in registry key paths

---

internal/install/execution/link_generator.go
internal/install/execution/mock_link_generator.go
internal/install/execution/platform_link_generator.go
internal/install/execution/terminal_reporter.go

At Agent Control team we received a report about the Fleet link that the newrelic-cli process outputs on installation was broken ([ref](https://newrelic.slack.com/archives/C084EDJFAF8/p1742857120953389)). Looking into it, just seems that when regardless of the environment where the installation takes place we always return the US URL.
This PR fix this by unifying how the Fleet link is constructed
refernce:
[slack](https://newrelic.slack.com/archives/C01PTDC51K2/p1742980341026859) 🧵

fix(agent-control): link to fleet

---

internal/install/execution/link_generator.go
internal/install/execution/mock_link_generator.go
internal/install/execution/platform_link_generator.go
internal/install/execution/terminal_reporter.go

At Agent Control team we received a report about the Fleet link that the newrelic-cli process outputs on installation was broken ([ref](https://newrelic.slack.com/archives/C084EDJFAF8/p1742857120953389)). Looking into it, just seems that when regardless of the environment where the installation takes place we always return the US URL.
This PR fix this by unifying how the Fleet link is constructed
refernce:
[slack](https://newrelic.slack.com/archives/C01PTDC51K2/p1742980341026859) 🧵
Test:

fix(agent-control): Agent control short url fix

---

scripts/install.ps1

Issue mentioned in the [Jira Ticket](https://new-relic.atlassian.net/browse/NR-400198)
**Resolution done:-**
I updated the script code that removes the old logic that manually escaped square brackets ([, ]) in registry keys using -replace. This was unnecessary because PowerShell's -LiteralPath parameter can handle special characters in paths without requiring manual escaping. The old logic was error-prone and introduced parsing issues, such as "Missing type name after '['." By replacing it with -LiteralPath, the updated code simplifies the implementation, avoids these errors, and ensures compatibility with registry keys containing special characters. This change improves both the reliability and maintainability of the function.
I tested my changes after creating few test registery keys …

fix(script): Fixed error with Infra Guided Install on windows hosts

---

.github/workflows/release-publish-windows.yml
.github/workflows/release.yml

- Updated the ubuntu versions in release ymls. This is due to current version ubuntu-20.04 is recently deprecated and no longer supported. Followed below solution to fix it.
**Suggested solutions: https://github.com/actions/runner-images/issues/11101**

fix: Updated the ubuntu version in rel ymls

---

.goreleaser.yml

The GPG Key currently in use by the New Relic CLI expired on 27 April 2025; hence, a replacement of the key is needed.
For the replacement to be done, the ID of the GPG Key created has to be added to the GoReleaser config (as added by this PR) - following the merge of this PR, the `PGP_PRIVATE_KEY` attribute in the secrets of this repository shall be updated with the newly generated PGP Private Key. With both of these steps done, our releases should be back working again.

fix(build): adds updated GPG Key ID

---

internal/install/recipe_installer_test.go

In response to a recent request from the new team (`OTEL`/`OTELCOMM`) maintaining OpenTelemetry products at New Relic (who are now, the new owners of the OpenTelemetry recipe in the Open Install Library too), a request has been received to retire the Open Telemetry recipe since this is currently not in integrated use with installs, neither is this recipe being displayed anywhere in data sources in the Integrations & Agents page; which makes it safe for us to retire this recipe.
While all references to the recipe are supposed to exist in the Open Install Library, they have all been reverted via https://github.com/newrelic/open-install-library/pull/1208 (changes previously added via https://github.com/newrelic/open-install-library/pull/921) - dangling references left in the New Relic CLI …

fix(otel): remove dangling references to otel recipe

---

internal/install/recipe_installer.go

[Jira Ticket](https://new-relic.atlassian.net/browse/NR-377103)
**Problem:-**
Customers were encountering the following error during execution:
`Debug Error: 401 response returned: Invalid credentials provided. Missing API key or an invalid API key was provided.`
**Cause:-**
The 401 Unauthorized error occurred because the recipe attempted to authenticate with New Relic's API using a License Key, which is not valid for API authentication. API operations require a valid API Key (User API Key or Personal API Key).
**Solution:-**
This fix updates the code to only add the **InstallEventsReporter status subscriber** if a valid API Key is present in the active profile. This prevents attempts to authenticate with invalid credentials and avoids unnecessary 401 errors.
**Testing Results:-** No  401 …

fix: Add InstallEventsReporter only if API key is set

---

docs/cli/newrelic_install.md

- Added docs support for specific infra agent CLI installs.

fix: Add CLI docs support for specific infra agent CLI installs

---

.github/workflows/release.yml

This is a PR that include minor update where we are adding a new step in the release.yml file to copy the checksum file with a different name and push it to GIT release assets along with its respective signature file.
This changes are done for the minor request that was asked by the customer(E.ON) in this [WR](https://new-relic.atlassian.net/browse/NR-307933).
Changes for the checksum generation and adding the install scripts to the GIT release assets was done as part of https://github.com/newrelic/newrelic-cli/pull/1736 PR.
No Test validation SS is available as there is no way to test the changes in local, a realtime release is required to test the changes..
Any further changes on this will be part of other PR and this PR will be attached in the new one to keep a track of the PR's that …

feat(checksum): Add validations for checksum file upload

---

internal/install/recipes/process_evaluator.go

- Skipped LSASS.exe process to be processed for processMatch.

fix: Skip lsass.exe process from being processed

---

.github/workflows/release.yml

This is a PR that include minor update where we are changing the file name of the copied checksum file to checksums_sha256.txt to add checksum type context in the name of the file.
This changes are done for the minor request that was asked by the customer(E.ON) in this [WR](https://new-relic.atlassian.net/browse/NR-307933).
Changes for the checksum generation and adding the install scripts to the GIT release assets was done as part of https://github.com/newrelic/newrelic-cli/pull/1736 PR.
Subsequent changes are present in [this](https://github.com/newrelic/newrelic-cli/pull/1743) PR
No Test validation SS is available as there is no way to test the changes in local, a realtime release is required to test the changes..
Any further changes on this will be part of other PR and this PR will be …

fix(checksum): Update copied checksum file name
